version: '3.4'
services:
  db:
    image: ferlintec/mysql-simian
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: simian
    ports:
      - "3308:3306"
    networks:
      - ferlintec-network
  ferlintec-simian:
    image: ferlintec/simian
    restart: always
    build: ./SimianDNAVerification
    working_dir: /SimianDNAVerification
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./SimianDNAVerification:/SimianDNAVerification
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - ferlintec-network
networks:
    ferlintec-network:
        driver: bridge